# -*- coding: utf-8 -*-
"""restaurant-sales-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UjTxfBIn9r-JN7oKPsnwPHkP-faCqEV

# Sales Data Analysis with Python

### (A part of Big Data Analysis)

-------------

#### Restaurant Sales Dataset
***
Here,

We have the sales data of a restaurant company from different cities (countries).

This data is available in CSV file format. We are going to analyze and visualize this data.

-------------

### Importing the Required Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install --quiet streamlit pyngrok plotly==5.18.0 pandas matplotlib seaborn

!pip install --quiet --upgrade pyngrok

import sys
import importlib
for pkg in ("streamlit","pyngrok","plotly","pandas","matplotlib","seaborn"):
    m = importlib.import_module(pkg)
    print(pkg, "version:", getattr(m, "__version__", "unknown"))
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Plot settings
# %matplotlib inline
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

"""### Importing the dataset"""

data = pd.read_csv("/content/Sales-Data-Analysis.csv")

data

data.info()                                      # to show some basic informations about the dataset

"""#### Consider the Manager column"""

data.head()

data.Manager

data.Manager.unique()                     # to show all the unique values of the column

data.Manager.nunique()                      # to show count of unique values present in the column

data['Manager'] = data['Manager'].str.strip().str.replace(r'\s+', ' ', regex=True)   # to remove extra spaces in names

data.head(20)

data['Manager'].unique()             # to show all the unique values of the column

data['Manager'].nunique()             # to show count of unique values present in the column

data

"""# Converting the datatype of columns"""

data.info()                               # to get some basic info about the dataframe

data.Quantity = data.Quantity.astype(float)  # to change the datatype of a column

data.info()                                  # to get some basic info about the dataframe

data.Quantity = data.Quantity.round()              # to round-off the values of a column

data.Quantity

data.Quantity = data.Quantity.astype(int)             # to change the datatype of a column

data['Quantity']

data['Order ID'] = data['Order ID'].astype(int)        # to change the datatype of a column
data['Price'] = data['Price'].astype(float)            # to change the datatype of a column

data.info()                                       # to get some basic info about the dataframe

data.Date = pd.to_datetime(data.Date, format = 'mixed')          # to convert the datatype into datetime format

data.Date.dtype                                # to check the datatype of any column

data.info()

data

"""----------

# Analyzing the Data

#Most Preferred Payment Method
"""

data.head()                       # to show top 5 records of the dataframe

data['Payment Method'].unique()                       # to show the unique values of a column

data['Payment Method'].nunique()                      # to show the count of unique values in a column

data['Payment Method'].value_counts()                 # to show the unique values of a column with their counts

data['Payment Method'].value_counts(normalize=True)*100    # to get the result in percentage

data['Payment Method'].value_counts().plot(kind='bar') ;   # to draw the bar graph

"""# Most Selling Product
- By Quantity
- By Revenue

#### By Quantity
"""

data.head()

data.groupby('Product')['Quantity'].sum()            # to make the group of unique values of a column

data.groupby('Product')['Quantity'].sum().sort_values(ascending=False)   # to sort the result

most_quantity = data.groupby('Product')['Quantity'].sum().sort_values(ascending=False)
most_quantity

type(most_quantity)                   # to the type of the variable

most_quantity = most_quantity.reset_index()     # To convert the index of a Series into a column to form a DataFrame
most_quantity

type(most_quantity)                   # to the type of the variable

plt.figure(figsize = (9,4))
plt.bar(most_quantity['Product'], most_quantity['Quantity'], color = ['red', 'black', 'green', 'yellow', 'cyan'], width=0.4)
plt.title("Most Selling Product - By Quantity")
plt.xlabel("Product")
plt.ylabel("Quantity");

"""#### By Revenue"""

data.head()

data['Revenue'] = data['Price'] * data['Quantity']       # to create a new column 'Revenue'

data

data.groupby('Product')['Revenue'].sum().sort_values(ascending = False) # to make the group of unique values of a column

most_revenue = data.groupby('Product')['Revenue'].sum().sort_values(ascending = False)
most_revenue

most_revenue = most_revenue.reset_index()         # To convert the index of a Series into a column to form a DataFrame
most_revenue

plt.figure(figsize=(9, 4))
plt.bar(most_revenue['Product'], most_revenue['Revenue'], color = ['green', 'red', 'black', 'yellow', 'cyan'], width = 0.3);
plt.title("Most Selling Product - By Revenue")       # setting the title
plt.xlabel("Product")                                # setting the x-axis label
plt.ylabel("Revenue");                               # setting the y-axis label

"""# Which city had maximum revenue
##### or
##### Which Manager earned maximum revenue
"""

data

data.City.unique()                       # to check the unique values of the column 'City'

data.City.nunique()                      # to check the count of unique values of the column 'City'

data.groupby('City')['Revenue'].sum().sort_values(ascending=False)   # using groupby on 'City' & 'Revenue' column

data.Manager.nunique()                   # to check the count of unique values of the column 'Manager'

data.Manager.unique()                   # to check the unique values of the column 'Manager'

data.groupby('Manager')['Revenue'].sum().sort_values(ascending=False)   # using groupby on 'Manager' & 'Revenue' column

"""# Date wise revenue"""

data.head()

data.Date.dtype

data.info()

data.plot('Date', 'Revenue', color='red', linewidth=2, figsize=(9,4))
plt.title("Date wise Revenue")                        # setting the title
plt.xlabel("Date")                                    # setting the x-axis label
plt.ylabel("Revenue")                                 # setting the y-axis label
plt.show()

"""# Average Revenue"""

data.head()

data['Revenue'].mean()

"""#### Average Revenue of November & December month"""

data.head()

data['Month'] = data['Date'].dt.month              # creating a new column showing Month only

data

m11 = data[data['Month'] == 11]          # filtering the records with month '11'
m11

m11.Revenue.mean()                           # to show the mean revenue

m12 = data[data.Month == 12]                  # filtering the records with month '12'
m12

m12.Revenue.mean()                                  # to show the mean revenue

"""# Standard Deviation of Revenue and Quantity ?"""

data['Quantity'].std()

data['Revenue'].std()

"""# Variance of Revenue and Quantity ?"""

data['Quantity'].var()

data['Revenue'].var()

"""# Is revenue increasing or decreasing over time?"""

data.head()

m11 = data[data['Month'] == 11]          # filtering the records with month '11'
m11

m11['Revenue'].sum()

m12 = data[data.Month == 12]                  # filtering the records with month '12'
m12

m12.Revenue.sum()

"""# Average 'Quantity Sold' & 'Average Revenue' for each product ?"""

data.head()

data.groupby('Product')[['Quantity', 'Revenue']].agg({'Quantity':'mean', 'Revenue':'mean'})  # using agg() with groupby()

"""##DASHBOARD

"""

!pip install plotly pandas numpy

import pandas as pd

df = pd.read_csv('/content/Sales-Data-Analysis.csv')
df.head()

import plotly.express as px

df["Revenue"] = df["Price"] * df["Quantity"]
df['Total Sales'] = df['Revenue']
fig1 = px.bar(
    df.groupby("Product")["Revenue"].sum().reset_index(),
    x="Product",
    y="Revenue",
    title="Total Revenue by Product",
    text_auto=True
)
fig1.show()

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

df['Month'] = df['Date'].dt.to_period("M")

monthly = df.groupby('Month')['Total Sales'].sum().reset_index()
monthly['Month'] = monthly['Month'].astype(str)

fig2 = px.line(
    monthly,
    x="Month",
    y="Total Sales",
    markers=True,
    title="Monthly Sales Trend"
)

fig2.show()

fig3 = px.bar(
    df.groupby("Product")["Quantity"].sum().sort_values(ascending=False).head(10).reset_index(),
    x="Quantity",
    y="Product",
    orientation="h",
    title="🍔 Top 10 Best-Selling Products",
    text_auto=True
)

fig3.update_layout(xaxis_title="Quantity Sold", yaxis_title="Product")
fig3.show()

fig4 = px.pie(
    df,
    names="Payment Method",
    values="Total Sales",
    title="Payment Method Share",
    hole=0.4
)
fig4.show()

fig5 = px.bar(
    df.groupby("City")["Revenue"].sum().reset_index(),
    x="City",
    y="Revenue",
    text_auto=True,
    title="City-Wise Total Revenue"
)
fig5.show()

!pip -q install plotly==5.18.0 kaleido

import os
import glob
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from IPython.display import display, HTML

possible = glob.glob('/content/Sales-Data-Analysis.csv') + glob.glob('/content/*.csv') + glob.glob('*.csv')
if len(possible) == 0:
    raise FileNotFoundError("No CSV found in typical locations. Upload your CSV to Colab and re-run.")
csv_path = possible[0]
print("Using CSV:", csv_path)

df = pd.read_csv(csv_path)
print("Original columns:", list(df.columns))
df.columns = [c.strip() for c in df.columns]

for col in ['Price', 'Quantity', 'Revenue', 'Total Sales']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col].astype(str).str.replace(',',''), errors='coerce')

if 'Quantity' in df.columns:
    df['Quantity'] = df['Quantity'].round().fillna(0).astype(int)

date_col = None
for candidate in ['Date', 'Order Date', 'OrderDate', 'date']:
    if candidate in df.columns:
        date_col = candidate
        break
if date_col is None:
    raise KeyError("No Date/Order Date column found. Rename it to 'Date' or 'Order Date'.")
df[date_col] = pd.to_datetime(df[date_col].astype(str), dayfirst=True, errors='coerce')
if df[date_col].isna().sum() > 0:
    print(f"Warning: {df[date_col].isna().sum()} rows could not be parsed as dates (set to NaT).")

df = df.rename(columns={date_col: 'Date'})

if 'Total Sales' in df.columns:
    df['Total_Sales'] = df['Total Sales']
elif 'Revenue' in df.columns:
    df['Total_Sales'] = df['Revenue']
else:
    if ('Price' in df.columns) and ('Quantity' in df.columns):
        df['Total_Sales'] = df['Price'] * df['Quantity']
    else:
        raise KeyError("No 'Total Sales' or 'Revenue' and cannot compute (missing Price or Quantity).")

if 'Category' not in df.columns:
    def infer_category(prod):
        p = str(prod).lower()
        if any(x in p for x in ['burger','chicken','sandwich','main','rice','noodl','curry','paneer']):
            return 'Main Course'
        if any(x in p for x in ['fries','sides','side','starter','samosa','spring']):
            return 'Starters'
        if any(x in p for x in ['beverage','tea','coffee','drink','shake','cold drink']):
            return 'Drinks'
        if any(x in p for x in ['ice cream','cake','brownie','dessert']):
            return 'Desserts'
        return 'Other'
    df['Category'] = df.get('Product', df.get('Item Name', '')).apply(infer_category)

if 'Product' in df.columns:
    df = df.rename(columns={'Product':'Item'})
elif 'Item Name' in df.columns:
    df = df.rename(columns={'Item Name':'Item'})

for c in ['Item', 'Category', 'Payment Method', 'Manager', 'City', 'Branch']:
    if c in df.columns:
        df[c] = df[c].astype(str).str.strip()

df = df[df['Date'].notna()].copy()
df['YearMonth'] = df['Date'].dt.to_period('M').astype(str)
df['Month'] = df['Date'].dt.month
df['DayOfWeek'] = df['Date'].dt.day_name()

print("Cleaned columns:", list(df.columns))
display(df.head())

PALETTE = {
    "Main Course": "#0D47A1",
    "Starters": "#FF5722",
    "Drinks": "#FFC107",
    "Desserts": "#4CAF50",
    "Side Dishes": "#9C27B0",
    "Other": "#607D8B"
}
FALLBACK_COLORS = px.colors.qualitative.Bold

cat_sales = df.groupby('Category', as_index=False)['Total_Sales'].sum().sort_values('Total_Sales', ascending=False)

monthly = df.groupby('YearMonth', as_index=False)['Total_Sales'].sum().sort_values('YearMonth')

top_items_revenue = df.groupby('Item', as_index=False)['Total_Sales'].sum().sort_values('Total_Sales', ascending=False).head(10)
top_items_qty = df.groupby('Item', as_index=False)['Quantity'].sum().sort_values('Quantity', ascending=False).head(10)

if 'Payment Method' in df.columns:
    payment_share = df.groupby('Payment Method', as_index=False)['Total_Sales'].sum().sort_values('Total_Sales', ascending=False)
else:
    payment_share = pd.DataFrame(columns=['Payment Method', 'Total_Sales'])

if 'Branch' in df.columns:
    branch_sales = df.groupby('Branch', as_index=False)['Total_Sales'].sum().sort_values('Total_Sales', ascending=False)
else:
    branch_sales = pd.DataFrame()

fig = make_subplots(
    rows=3, cols=2,
    column_widths=[0.6, 0.4],
    row_heights=[0.35, 0.35, 0.30],
    specs=[[{"type":"bar"}, {"type":"scatter"}],
           [{"type":"bar"}, {"type":"pie"}],
           [{"type":"bar"}, {"type":"table"}]],
    subplot_titles=("Sales by Category", "Monthly Sales Trend", "Top 10 Items (Revenue)",
                    "Payment Method Share", "Branch Sales", "Top 10 Items (Quantity)")
)

fig.add_trace(
    go.Bar(
        x=cat_sales['Category'],
        y=cat_sales['Total_Sales'],
        marker_color=[PALETTE.get(c, FALLBACK_COLORS[i % len(FALLBACK_COLORS)]) for i,c in enumerate(cat_sales['Category'])],
        text=cat_sales['Total_Sales'].map(lambda x: f"${x:,.0f}"),
        textposition='auto',
        hovertemplate="%{x}<br>Sales: %{y:$,.0f}<extra></extra>"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=monthly['YearMonth'],
        y=monthly['Total_Sales'],
        mode='lines+markers',
        line=dict(width=3, color="#EF476F"),
        marker=dict(size=8),
        hovertemplate="%{x}<br>Sales: %{y:$,.0f}<extra></extra>"
    ),
    row=1, col=2
)

fig.add_trace(
    go.Bar(
        x=top_items_revenue['Total_Sales'][::-1],
        y=top_items_revenue['Item'][::-1],
        orientation='h',
        marker_color="#118AB2",
        text=top_items_revenue['Total_Sales'].map(lambda x: f"${x:,.0f}")[::-1],
        textposition='auto',
        hovertemplate="%{y}<br>Revenue: %{x:$,.0f}<extra></extra>"
    ),
    row=2, col=1
)

if not payment_share.empty:
    fig.add_trace(
        go.Pie(
            labels=payment_share['Payment Method'],
            values=payment_share['Total_Sales'],
            hole=0.45,
            sort=False,
            textinfo='percent+label',
            marker=dict(colors=px.colors.sequential.Plasma[:len(payment_share)])
        ),
        row=2, col=2
    )
else:
    fig.add_trace(go.Scatter(x=[0], y=[0], mode='markers', marker=dict(opacity=0)), row=2, col=2)

if not branch_sales.empty:
    fig.add_trace(
        go.Bar(
            x=branch_sales['Branch'],
            y=branch_sales['Total_Sales'],
            marker_color="#06D6A0",
            text=branch_sales['Total_Sales'].map(lambda x: f"${x:,.0f}"),
            textposition='auto',
            hovertemplate="%{x}<br>Sales: %{y:$,.0f}<extra></extra>"
        ),
        row=3, col=1
    )
else:
    pass

table_df = top_items_qty.copy()
fig.add_trace(
    go.Table(
        header=dict(values=["Item", "Quantity"], fill_color="#003f5c", font=dict(color='white', size=12)),
        cells=dict(values=[table_df['Item'], table_df['Quantity']], fill_color="#f0f4f8")
    ),
    row=3, col=2
)

fig.update_layout(
    title_text="🍽️ Restaurant Sales BI Dashboard",
    template='plotly_white',
    height=950,
    showlegend=False,
    margin=dict(l=40, r=20, t=100, b=40),
    paper_bgcolor="#F8FAFC",
    plot_bgcolor="#F8FAFC",
    font=dict(family="Segoe UI, Arial", size=12, color="#111111")
)


fig.update_yaxes(tickformat="$,~", row=1, col=1)
fig.update_yaxes(tickformat="$,~", row=1, col=2)
fig.update_xaxes(tickangle=-45, row=1, col=1)

fig.show()

summary = {
    "Total Orders": int(df['Order ID'].nunique()) if 'Order ID' in df.columns else len(df),
    "Total Revenue": df['Total_Sales'].sum(),
    "Average Order Value": df['Total_Sales'].mean(),
    "Total Items": df['Item'].nunique()
}
display(HTML("<h3>Quick Summary</h3>"))
display(pd.DataFrame.from_dict(summary, orient='index', columns=['Value']))

fig.write_html("restaurant_dashboard.html")

from google.colab import files
files.download("restaurant_dashboard.html")

"""## End of Project
_________
"""